(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cc" 'org-capture)
(global-set-key "\C-cb" 'org-iswitchb)

(load "~/.dotfiles/emacs/org-mode/notes.el" t)
(load "~/.dotfiles/emacs/org-mode/tasks.el" t)
(load "~/.dotfiles/emacs/org-mode/agenda.el" t)
(load "~/.dotfiles/emacs/org-mode/time-tracking.el" t)
(load "~/.dotfiles/emacs/org-mode/reporting.el" t)
(load "~/.dotfiles/emacs/org-mode/gcal.el" t)
